### ISSUE TITLE
How do I specify the loglevel?

### ISSUE THREAD

**Issue by najamelan** [WorldSEnder/tracing-web#3]
Tried with:
`.with_max_level(tracing::Level::DEBUG)` on either the `fmt_layer` or the `registry()`, but I get an error like:

```
error[E0599]: the method `with_max_level` exists for struct `Layer<_>`, but its trait bounds were not satisfied
   --> src/entrypoint.rs:101:4
    |
100 |       let fmt_layer = tracing_subscriber::fmt::layer()
    |  _____________________-
101 | |         .with_max_level(tracing::Level::DEBUG)
    | |_________-^^^^^^^^^^^^^^
    |
   ::: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/fmt/fmt_layer.rs:62:1
    |
62  | / pub struct Layer<
63  | |     S,
64  | |     N = format::DefaultFields,
65  | |     E = format::Format<format::Full>,
66  | |     W = fn() -> io::Stdout,
67  | | > {
    | | -
    | | |
    | |_doesn't satisfy `_: MakeWriterExt<'_>`
    |   doesn't satisfy `tracing_subscriber::fmt::Layer<_>: MakeWriter<'_>`
    |
    = note: the following trait bounds were not satisfied:
            `tracing_subscriber::fmt::Layer<_>: MakeWriter<'_>`
            which is required by `tracing_subscriber::fmt::Layer<_>: MakeWriterExt<'_>`
            `&tracing_subscriber::fmt::Layer<_>: MakeWriter<'_>`
            which is required by `&tracing_subscriber::fmt::Layer<_>: MakeWriterExt<'_>`
            `&mut tracing_subscriber::fmt::Layer<_>: MakeWriter<'_>`
            which is required by `&mut tracing_subscriber::fmt::Layer<_>: MakeWriterExt<'_>`
```
or:

```
error[E0599]: the method `with_max_level` exists for struct `Registry`, but its trait bounds were not satisfied
   --> src/entrypoint.rs:110:4
    |
109 | /     tracing_subscriber::registry()
110 | |         .with_max_level(tracing::Level::DEBUG)
    | |         -^^^^^^^^^^^^^^ method cannot be called on `Registry` due to unsatisfied trait bounds
    | |_________|
    | 
    |
   ::: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:92:1
    |
92  |   pub struct Registry {
    |   -------------------
    |   |
    |   doesn't satisfy `Registry: MakeWriter<'_>`
    |   doesn't satisfy `Registry: MakeWriterExt<'_>`
    |
    = note: the following trait bounds were not satisfied:
            `Registry: MakeWriter<'_>`
            which is required by `Registry: MakeWriterExt<'_>`
            `&Registry: MakeWriter<'_>`
            which is required by `&Registry: MakeWriterExt<'_>`
            `&mut Registry: MakeWriter<'_>`
            which is required by `&mut Registry: MakeWriterExt<'_>`
```

**Comment by WorldSEnder** [comment]
You most likely want to use the `.with_filter(LevelFilter::DEBUG)`, as described in the [`tracing_subscriber`](https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/layer/index.html#per-layer-filtering) doc about event filtering on layers. This subsumes the functionality of `with_max_level` which is available for `Subscriber` and `MakeWriter`. For more specific questions though, refer to their docs.

**Comment by najamelan** [comment]
Thanks a lot for getting back on this. I missed that. I thought filter needed to be an actual closure etc, so I thought there must be a better way. I'll try this tonight. I admit I get lost in the tracing API. Kind of confusing Layer's don't have the same method as the rest.

**Comment by WorldSEnder** [comment]
> Kind of confusing Layer's don't have the same method as the rest.

I agree, finding your way through the multiple traits and extensions can be a hassle. Even more confusing [I found out](https://github.com/tokio-rs/tracing/issues/641) that they will rename "Layer" -> "Subscriber" and "Subscriber" -> "Collect" in an upcoming release (found the docs for the master branch first) - so make sure you're using the one for the released version. That will be a fun time to rewrite the docs ^^ Feel free to close the issue if it ends up working for you.

**Comment by najamelan** [comment]
It compiles, but it still outputs trace logs:
```rust
	let fmt_layer = tracing_subscriber::fmt::layer()
		.with_ansi(false) // Only partially supported across browsers
		// .with_timer(UtcTime::rfc_3339()) // std::time is not available in browsers
		.without_time()
		.with_writer(MakeConsoleWriter) // write events to the console
		.with_filter(tracing::level_filters::LevelFilter::INFO)
		;
```

**Comment by WorldSEnder** [comment]
Sorry, but I can not reproduce this. The above code works as expected when pasted into the example in this repo, writing only Info level events (and those considered less verbose, such as errors) while omitting more verbose events such as Debug level ones. If you're still confused about the usage, consider taking it up with the devs of `tracing-subscriber` or share a full Minimal, Reproducible Example (with .lock file so rule out any version mismatches) instead of just snippets.

**Comment by najamelan** [comment]
Hi, thanks for bearing with me. I don't know what happened. I re-tested today and it worked. Only difference I can see is that rebooting cleared the compilation artifacts. In any case, good news. This is the first time I have a way of logging tracing in wasm that actually works. Thanks a dime.
